"""Add category to performance

Revision ID: 389ef8b63d21
Revises: 68c35f2c1c80
Create Date: 2026-01-31 23:53:53.465370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389ef8b63d21'
down_revision: Union[str, Sequence[str], None] = '68c35f2c1c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'category')
    # ### end Alembic commands ###
