"""Add performance table

Revision ID: 68c35f2c1c80
Revises: ff8c4c649074
Create Date: 2026-01-31 22:49:34.441920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c35f2c1c80'
down_revision: Union[str, Sequence[str], None] = 'ff8c4c649074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('construction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_id'), 'performance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_id'), table_name='performance')
    op.drop_table('performance')
    # ### end Alembic commands ###
