"""Expand performance metadata

Revision ID: 74be88f448d8
Revises: 389ef8b63d21
Create Date: 2026-02-01 16:37:07.725159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74be88f448d8'
down_revision: Union[str, Sequence[str], None] = '389ef8b63d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('performance', sa.Column('job_main_category', sa.String(), nullable=True))
    op.add_column('performance', sa.Column('job_sub_category', sa.String(), nullable=True))
    op.add_column('performance', sa.Column('site_type', sa.String(), nullable=True))
    op.add_column('performance', sa.Column('site_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'site_location')
    op.drop_column('performance', 'site_type')
    op.drop_column('performance', 'job_sub_category')
    op.drop_column('performance', 'job_main_category')
    op.drop_column('performance', 'year')
    # ### end Alembic commands ###
